### ISSUE TITLE
[Feature] Break Action

### ISSUE THREAD

**Issue by Fire0nTop** [TheMisterFish/Fabric_OfflinePlayersReworked#30]
**Is your feature request related to a problem? Please describe.**
Just an added Action

**Describe the solution you'd like**
The Command /offline break feature

**Additional context**

**Versions**
- Minecraft: 1.21.1 fabric

**Comment by wetrustinprize** [comment]
Hey there! I was needing this feature too, but if we read the mod code it already handles block breaking.

After some investigation, we've discovered that the way to break blocks you just need to `attack:0`, which will result in holding the M1 because there is no delay between attacks.

I think this is nice to be documented in the mod's description, but there is no need to implement it in the code.

**Comment by TheMisterFish** [comment]
I like the idea of adding `/offline break` which will do the same as `/offline attack:0`.

**Comment by TheMisterFish** [comment]
@Fire0nTop @wetrustinprize I've added it in 1.0.8
You can also use it with interval, it will break the block until it is broken before resetting the interval.

**Comment by wetrustinprize** [comment]
awesome! Thanks for the implementation :)
